Capgemini/powerapps-specflow-bindings

- CONTRIBUTING.md
- GitVersion.yml
- azure-pipelines.yml
- bindings/src/Capgemini.PowerApps.SpecFlowBindings/Capgemini.PowerApps.SpecFlowBindings.nuspec
- bindings/tests/Capgemini.PowerApps.SpecFlowBindings.UiTests/CodeCoverage.runsettings
***NO_CI*** the resulting commit of this PR needs to be tagged with the initial version before the CI pipeline can run
GitVersion has been configured in mainline mode. This means that it will automatically increment to a full version on each commit in master. 
Using default version bump regex:
```yaml
major-version-bump-message: '\+semver:\s?(breaking|major)'
minor-version-bump-message: '\+semver:\s?(feature|minor)'
patch-version-bump-message: '\+semver:\s?(fix|patch)'
```
Patch version incremented by default. For more info: https://gitversion.net/docs/more-info/version-increments
Pipeline has also been updated to pack the NuGet package using the version from GitVersion.
**Note: we will need to stop using pre-release tags as mainline mode on GitVersion doesn't support it. I believe this …
> Added GitVersion to automatically increment package and assembly version

- bindings/tests/Capgemini.PowerApps.SpecFlowBindings.UiTests/Capgemini.PowerApps.SpecFlowBindings.UiTests.csproj
- bindings/tests/Capgemini.PowerApps.SpecFlowBindings.UiTests/CodeCoverage.runsettings
The UI tests were failing to run due to not being able to find the .runsettings file that was configured. 
Updated the UI test project to copy the .runsettings file to the output directory (and thus get published in the test artifact, accessible to the test job)
> Fixed issue with UI tests not running with code coverage in pipeline

- azure-pipelines.yml
WhiteSource Bolt can be used to detect security or licensing issues.
Integrated WhiteSource Bolt into the CI pipeline.
> ci: added whitesource bolt to build stage

- azure-pipelines.yml
GitHub releases are a useful way of tagging releases in the commit history and tracking bugs and issues closed in each release.
The CI pipeline will now automatically create a GitHub release on when: 
- it has successfully deployed to NuGet.org 
- the pipeline is running on the master branch
> [ci] updated pipeline to automatically create GitHub release

- bindings/src/Capgemini.PowerApps.SpecFlowBindings/Capgemini.PowerApps.SpecFlowBindings.csproj
- bindings/src/Capgemini.PowerApps.SpecFlowBindings/FileDataRepository.cs
- bindings/src/Capgemini.PowerApps.SpecFlowBindings/PowerAppsStepDefiner.cs
- bindings/src/Capgemini.PowerApps.SpecFlowBindings/TestDriver.cs
- driver/src/TestDriver.ts
- driver/src/TestEvents.ts
- driver/src/tests/TestDriver.spec.ts
Unhandled exceptions encountered by the driver when using the `Given I have created` step binding (or any binding that makes asynchronous calls to the driver) would result in a timeout exception rather than a meaningful exception that could be used to fix the problem. Fixes #8.
A slight refactor addresses this problem by returning a string to the callback with a prefix that identifies it as an exception. This is because `IJavaScriptExecutor.executeAsyncScript()` doesn't return JavaScript `Error`s as their own identifiable type.
> fix: error messages not returned when test data setup fails

- azure-pipelines.yml
Automatic release creation was:
- missing assets due to pointing to the wrong folder. 
- using an incorrect version number due to a missing pipeline variable
- not creating pre-release versions
Fixed the issues above in the pipeline.
> ci: fixed failing automatic release creation 

- bindings/src/Capgemini.PowerApps.SpecFlowBindings/Steps/LookupSteps.cs
`When I select the '(.*)' view in the lookup` step was throwing a null reference exception.
Corrects an issue with a CSS selector.
Fixes #30
> fix: switch lookup view throws null reference

- azure-pipelines.yml
- templates/include-build-and-test-steps.yml
The version number was not being set correctly in the deployment stage of the release. This is because the GitVersion pipeline variable was not set by the GitVersion task. Output variables are required to use variables across stages.
Adds a task after the GitVersion task to set an output variable with the SemVer value. This can then be referenced in the deployment stage.
> ci: fix version number set in automatic release

- README.md
- templates/include-build-and-test-steps.yml
The ESLint report paths property was not able to find the report using a relative path.
Updated to pipeline to use an absolute path.
> ci: fixed eslint integration with sonarcloud

- bindings/src/Capgemini.PowerApps.SpecFlowBindings/build/Capgemini.PowerApps.SpecFlowBindings.targets
Unable to build a consuming project due to the build being unable to find specflow.driver.js
This file was renamed in #32 but the build targets were not updated to use the new file name.
> fix: build targets unable to find driver.js

- azure-pipelines.yml
- bindings/src/Capgemini.PowerApps.SpecFlowBindings/TestDriver.cs
Some step bindings that rely on the `GetTestRecordReference()` method were failing.
Makes the call to the driver synchronous rather than asynchronous.
> fix: error that occurred for steps that rely on alias references

- bindings/src/Capgemini.PowerApps.SpecFlowBindings/TestDriver.cs
Several bindings were failing due to a missing `return` keyword.
Added a new private method so that we only need to pass the driver function call and additional boilerplate is automatically added.
> fix: fixed a number of failing bindings

- bindings/src/Capgemini.PowerApps.SpecFlowBindings/Steps/LookupSteps.cs
- bindings/tests/Capgemini.PowerApps.SpecFlowBindings.UiTests/LookupSteps.feature
Adds the ability to click a related lookup field on the form.
New behaviour that is missing from easyrepro. Uses existing elements and extends it.
> New Lookup Binding with a test to cover it

- bindings/tests/Capgemini.PowerApps.SpecFlowBindings.UiTests/Data/data decorated with faker moustache syntax.json
- driver/src/data/fakerPreprocessor.ts
- driver/test/data/fakerPreprocessor.spec.ts
JSON syntax was mistakenly being interpreted as faker syntax. A nested lookup at the bottom of the JSON would end with `}}`, causing faker to run.
Runs faker on JSON property values rather than the JSON as a whole.
> fix: faker error for nested lookups in test data

- bindings/src/Capgemini.PowerApps.SpecFlowBindings/Capgemini.PowerApps.SpecFlowBindings.csproj
- bindings/src/Capgemini.PowerApps.SpecFlowBindings/Steps/GridSteps.cs
- bindings/src/Capgemini.PowerApps.SpecFlowBindings/packages.config
- bindings/tests/Capgemini.PowerApps.SpecFlowBindings.UiTests/GridSteps.feature
Grid column sorting is fixed in a later version of EasyRepro than we were dependent on. Unfortunately, it was a breaking change - so users wouldn't have been able to fix this by updating the EasyRepro package dependency alone.
Updates to the latest version of EasyRepro and updates the step binding to capture the additional parameter that is required.
> fix: grid column sorting

- bindings/src/Capgemini.PowerApps.SpecFlowBindings/Steps/LoginSteps.cs
A 'What's New' pop-up, appearing since the October 2020 wave 2 release, has been intercepting clicks.
Closes any such pop-ups on login (if they exist).
> fix: 'what's new' pop-ups intercepting clicks

- bindings/src/Capgemini.PowerApps.SpecFlowBindings/Steps/EntitySubGridSteps.cs
Fixes #10. `Then the subgrid contains a record with '(.*)' in the '(.*)' field` was asserting against values retrieved from JavaScript rather than from the UI. This resulted in dates being compared with something like `Tue Mar 24 2015 17:00:00 GMT-0700 (Pacific Daylight Time)`.
Now compares against values as shown in the UI.
> fix: subgrid binding asserting against JS values

- README.md
- bindings/src/Capgemini.PowerApps.SpecFlowBindings/PowerAppsStepDefiner.cs
- bindings/tests/Capgemini.PowerApps.SpecFlowBindings.UiTests/power-apps-bindings.yml
Resolves #49. As documented [here](https://docs.microsoft.com/en-us/azure/devops/pipelines/test/continuous-test-selenium?view=azure-devops#decide-how-you-will-deploy-and-test-your-app), Microsoft recommend that you use the Web Drivers that are preinstalled on Microsoft Hosted agents, this avoids a version mismatch between Chrome and ChromeDriver. Prior to this commit, there was no way to make use of these environment variables.
The BrowserOptions for EasyRepro allows for a driversPath variable to be provided. This commit adds logic to allow for this to be an Environment Variable. So the environment variables stated in the Microsoft Docs can be supplied. To run the ui tests for this repo locally, where the driver .exe is outputted to bin, simply create an environment variable for …
> feat: allow driversPath to be environment variable

- bindings/src/Capgemini.PowerApps.SpecFlowBindings/Extensions/WebClientExtensions.cs
- bindings/src/Capgemini.PowerApps.SpecFlowBindings/Steps/CommandBarSteps.cs
- bindings/src/Capgemini.PowerApps.SpecFlowBindings/Steps/EntitySubGridSteps.cs
- bindings/tests/Capgemini.PowerApps.SpecFlowBindings.UiTests/Hooks/EasyReproSelectorFixHooks.cs
- bindings/tests/Capgemini.PowerApps.SpecFlowBindings.UiTests/RelatedGridSteps.feature
- driver/src/data/deepInsertService.ts
- driver/test/data/deepInsertService.spec.ts
- templates/include-build-and-test-steps.yml
When using the `Given '(.*)' has created '(.*)' binding, the root record would be correctly created as the impersonated user. However, related records would continue to be created as the logged in user.
Passes the overridden repository to the private methods that were continuing to use the default repository.
> fix: related record creation not impersonated

- bindings/src/Capgemini.PowerApps.SpecFlowBindings/Steps/TimelineSteps.cs
- bindings/tests/Capgemini.PowerApps.SpecFlowBindings.UiTests/BusinessProcessFlowSteps.feature
- bindings/tests/Capgemini.PowerApps.SpecFlowBindings.UiTests/DialogSteps.feature
- bindings/tests/Capgemini.PowerApps.SpecFlowBindings.UiTests/EntitySteps.feature
- bindings/tests/Capgemini.PowerApps.SpecFlowBindings.UiTests/QuickCreateSteps.feature
- bindings/tests/Capgemini.PowerApps.SpecFlowBindings.UiTests/TimelineSteps.feature
To deliver the feature request in #81 
Adds a step binding that allows the test to click the create button for a custom activity entity from the timeline control.
> Added new Timeline step binding for clicking create for a custom activity

- bindings/src/Capgemini.PowerApps.SpecFlowBindings/Steps/LookupSteps.cs
Fixes #84.
Fixes the CSS selector used in this binding.
> Corrected selector for ThenICanSeeOnlyTheFollowingRecordsInTheLookup

- README.md
- bindings/src/Capgemini.PowerApps.SpecFlowBindings/Capgemini.PowerApps.SpecFlowBindings.csproj
- bindings/src/Capgemini.PowerApps.SpecFlowBindings/Configuration/BrowserOptionsWithProfileSupport.cs
- bindings/src/Capgemini.PowerApps.SpecFlowBindings/Configuration/ConfigHelper.cs
- bindings/src/Capgemini.PowerApps.SpecFlowBindings/Configuration/TestConfiguration.cs
- bindings/src/Capgemini.PowerApps.SpecFlowBindings/Extensions/BrowserTypeExtensions.cs
- bindings/src/Capgemini.PowerApps.SpecFlowBindings/Extensions/DirectoryInfoExtensions.cs
- bindings/src/Capgemini.PowerApps.SpecFlowBindings/Hooks/AfterScenarioHooks.cs
- bindings/src/Capgemini.PowerApps.SpecFlowBindings/Hooks/BeforeRunHooks.cs
- bindings/src/Capgemini.PowerApps.SpecFlowBindings/PowerAppsStepDefiner.cs
- bindings/src/Capgemini.PowerApps.SpecFlowBindings/Steps/LoginSteps.cs
- bindings/src/Capgemini.PowerApps.SpecFlowBindings/content/power-apps-bindings.yml
- bindings/tests/Capgemini.PowerApps.SpecFlowBindings.UiTests/Hooks/MockSolutionHooks.cs
- bindings/tests/Capgemini.PowerApps.SpecFlowBindings.UiTests/LookupSteps.feature
- bindings/tests/Capgemini.PowerApps.SpecFlowBindings.UiTests/power-apps-bindings.yml
- templates/include-build-and-test-steps.yml
Addresses #86 by using chrome/firefox user profiles to store history/cache enabling subsequent test cases to run faster.
If the use of profiles is enabled via the yml config, it will create a profile directory for each of the defined users, this is then passed as an argument to the underlying driver.
There is currently an issue with EasyRepro with the "Pick an Account" Microsoft login dialog which means the Login functionality is currently broken. A helper method has been added to the Login steps to clear these from the dialog allowing the OOTB login functionality to be used. This can be removed when https://github.com/microsoft/EasyRepro/pull/1143 is merged.
> feat: allow bypassing/streamlining of login using browser profiles

- bindings/src/Capgemini.PowerApps.SpecFlowBindings/Configuration/TestConfiguration.cs
- bindings/src/Capgemini.PowerApps.SpecFlowBindings/Hooks/BeforeRunHooks.cs
- bindings/src/Capgemini.PowerApps.SpecFlowBindings/PowerAppsStepDefiner.cs
Bug introduced in #88 where the GetUser logic would ignore the given alias and attempt to return the `currentUser`
Includes checks against the alias also removed ThreadLocal in favour of ThreadStatic
> fix: GetUser returning wrong users for alias

- bindings/src/Capgemini.PowerApps.SpecFlowBindings/Configuration/TestConfiguration.cs
- bindings/src/Capgemini.PowerApps.SpecFlowBindings/Extensions/IListExtensions.cs
If tests are running with process or AppDomain isolation then all of the test threads will cycle individually through the users in the same order. This can lead to API limits be still being reached despite configuring many different users for an alias - this is due to the fact that tests are only load balanced within a thread rather than across threads.
Shuffling the enumerators is an approximation that saves having to find a way to synchronise between AppDomains or processes.
> fix: users for alias not balanced across threads

- azure-pipelines-pull-request.yml
- azure-pipelines.yml
- templates/build-and-test-job.yml
- templates/build-and-test-stages.yml
Our ci/test environments have been disabled due to limited power platform storage. This impacts new code being tested for PR and the publishing of new package versions.
A copy from [powerapps-packagedeployer-template](https://github.com/Capgemini/powerapps-packagedeployer-template/pull/75) which creates a new environment every time and then disposes of it after manual validation.
> ci: provision environments dynamically

- bindings/src/Capgemini.PowerApps.SpecFlowBindings/ITestDriver.cs
- bindings/src/Capgemini.PowerApps.SpecFlowBindings/PowerAppsStepDefiner.cs
- bindings/src/Capgemini.PowerApps.SpecFlowBindings/TestDriver.cs
- driver/src/repositories/authenticatedRecordRepository.ts
- templates/build-and-test-job.yml
The authentication access token that is created expires if all the SpecFlow Bindings tests exceed one hour. 
Changes have been made to allow the access token to be refreshed after it has expired. The following files have been changed:
PowerAppsStepDefiner.cs
TestDriver.cs
ITestDriver.cs
Also modified build-and-test-job.yml to stop the jobs from running in parallel.
> fix: refresh app access token

- README.md
- bindings/src/Capgemini.PowerApps.SpecFlowBindings/Configuration/BrowserOptionsWithProfileSupport.cs
- bindings/src/Capgemini.PowerApps.SpecFlowBindings/Extensions/DriverOptionsExtensions.cs
- bindings/tests/Capgemini.PowerApps.SpecFlowBindings.UiTests/power-apps-bindings.yml
Allows additional capabilities to be passed to the `WebDriver`. This can be useful when running tests against a Selenium Grid.
Adds an `AdditionalCapabilities` property to the `TestConfig`. Can be read from the config file or set in code.
> feat: additional capabilities

- bindings/src/Capgemini.PowerApps.SpecFlowBindings/Steps/LookupSteps.cs
- bindings/tests/Capgemini.PowerApps.SpecFlowBindings.UiTests/LookupSteps.feature
Added a step to open the advanced lookup dialog for a lookup field. 
Uses the driver and CSS selector to find the link to click. 
> Ideally this would be EasyRepro code.
> feat: `I click to perform an advanced lookup on '(.*)' lookup` step

- README.md
- bindings/src/Capgemini.PowerApps.SpecFlowBindings/Configuration/BrowserOptionsWithProfileSupport.cs
- bindings/src/Capgemini.PowerApps.SpecFlowBindings/Configuration/UserConfiguration.cs
- bindings/src/Capgemini.PowerApps.SpecFlowBindings/Steps/LoginSteps.cs
- Changed the cookie policy in browser settings to allow 3rd party cookies. This blocked the log in and prompted the user to log in again right after logging in. [This page](https://learn.microsoft.com/en-us/answers/questions/1071292/sign-in-to-continue-some-components-of-this-app-re)  explains the error we ran into
- Added optional otp token property to user info. Now, a step utilizing the XrmApp.OnlineLogin.Login method can be created to work with MFA. I also modified the login step to use this method
This approach solves MFA being enabled on the test user and also fixes repeated login popup
> Fixed cookie setting, added support for MFA 

- bindings/src/Capgemini.PowerApps.SpecFlowBindings/Configuration/TestConfiguration.cs
The default behaviour of `TestConfig.GetUser` is to get the `current user` of an alias. If the test has previously called `GetUser` with a given alias, the same user will be returned as was returned previously. This works fine when running tests sequentially or in separate AppDomains, but when multiple tests execute concurrently in the same AppDomain, the wrong current user is returned.
Updates the `CurrentUsers` field to be `ThreadStatic`.
> fix: GetUser returns 'current user' from other tests

- bindings/src/Capgemini.PowerApps.SpecFlowBindings/Hooks/AfterScenarioHooks.cs
As explained in the SpecFlow [Hooks](https://docs.specflow.org/projects/specflow/en/latest/Bindings/Hooks.html?) docs, an unhandled exception thrown in a hook will prevent later hooks from executing. We capture screenshots in an `AfterScenario` hook before we clean-up the `WebDriver` in a subsequent `AfterScenario` hook. This means if the screenshot fails to capture for any reason (e.g. the Selenium Grid session has timed out), the clean-up hook will not happen and all subsequent tests will fail.
Wraps the screenshot capture in a try/catch.
> fix: screenshot failure prevents driver cleanup
